server:
  port: 8003

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/teacher
    username: chopractice
    password: chopractice

mybatis:
  mapper-locations: mappers/**/*.xml